apiVersion: v1
kind: Service
metadata:
  name: scaleway-proxy
  namespace: scaleway-proxy
  labels:
    app: scaleway-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: scaleway-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: scaleway-proxy-public
  namespace: scaleway-proxy
  labels:
    app: scaleway-proxy
    public: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: scaleway-proxy
