apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaleway-proxy-sa
  namespace: scaleway-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaleway-proxy-role
  namespace: scaleway-proxy
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "pods/log", "pods/exec", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaleway-proxy-rolebinding
  namespace: scaleway-proxy
subjects:
- kind: ServiceAccount
  name: scaleway-proxy-sa
  namespace: scaleway-proxy
roleRef:
  kind: Role
  name: scaleway-proxy-role
  apiGroup: rbac.authorization.k8s.io
