apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: demo-web-app
  labels:
    app: demo-web-app
    tier: frontend
spec:
  podSelector:
    matchLabels:
      app: demo-web-app
      tier: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: demo-web-app
          tier: frontend
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - ipBlock:
        cidr: 172.16.28.8/32
    ports:
    - protocol: TCP
      port: 3128
  - to:
    - namespaceSelector:
        matchExpressions:
        - {key: project, operator: In, values: [scaleway-k8s-egres-proxy]}
      podSelector:
        matchLabels:
          app: scaleway-proxy
    ports:
    - protocol: TCP
      port: 51122
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 172.16.0.0/12
        - 10.0.0.0/8
        - 192.168.0.0/16
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          project: scaleway-k8s-egres-proxy
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
