apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
commonLabels:
  app: multitenant-demo
  client/type: type-b
  egress/type: load-balancer
namespace: client-type-b
