apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: multitenant-demo-b
  namespace: client-type-b
  labels:
    app: multitenant-demo
    client/type: type-b
spec:
  podSelector:
    matchLabels:
      app: multitenant-demo
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              client/type: type-b
        - podSelector:
            matchLabels:
              app: multitenant-demo
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              project: scaleway-k8s-egres-proxy
          podSelector:
            matchLabels:
              app: scaleway-proxy
      ports:
        - protocol: TCP
          port: 51122
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 172.16.0.0/12
              - 10.0.0.0/8
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
