apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
commonLabels:
  app: egress-multitenant-demo
  project: scaleway-k8s-egres-proxy
namespace: client-type-a
