apiVersion: v1
kind: ServiceAccount
metadata:
  name: egress-multitenant-demo
  labels:
    app: egress-multitenant-demo
    tier: frontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: egress-multitenant-demo
  labels:
    app: egress-multitenant-demo
    tier: frontend
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egress-multitenant-demo
  labels:
    app: egress-multitenant-demo
    tier: frontend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: egress-multitenant-demo
subjects:
- kind: ServiceAccount
  name: egress-multitenant-demo
  namespace: client-a-demo
